config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "recipes#index"
  get '/recipes/:id', to: 'recipes#show', as: 'recipe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    @recipes = ProcessApiResponse::FilterRecipesInformation.new.call

    if @recipes.nil?
      redirect_back fallback_location: root_path
    end
  end

  def show
    @recipe = ProcessApiResponse::CompleteRecipeInformation.new(params[:recipe]).call

    if @recipe.nil?
      flash[:notice] = "Something bad happened. Try again latter."
      redirect_back fallback_location: root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :autolink, :no_intra_emphasis, :fenced_code_blocks]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoonChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="container text-center">
  <div class="row p-4">
    <h1>Marley Spoon Recipes</h1>
  </div>   

  <% @recipes.each do |recipe| %>
    <div class="row p-2">
      <div class="row justify-content-md-center p-3 border bg-light">
        <div class="col col-md-3 p-2">
          <%= image_tag(recipe[:photo], class: 'img-fluid') %>
        </div>
        <div class="col col-md-9 p-2">
          <div class="row p-4">
            <h4><%= recipe[:title] %></h4>
          </div>
          <div class="row p-5 justify-content-md-end">
            <%= link_to 'See more', recipe_path(id: recipe[:id], recipe: recipe), class: 'btn btn-outline-primary col-2' %>
          </div>
        </div>
      </div>   
    </div>   
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container text-center">
  <div class="row p-4">
    <h1><%= @recipe[:title] %></h1>
  </div>   

    <div class="row p-2">
      <div class="row justify-content-md-center p-3 border bg-light">
        <div class="col col-md-5 p-2">
          <%= image_tag(@recipe[:photo], class: 'img-fluid') %>
        </div>
        <div class="col col-md-7 p-2">
          <div class="row p-2 justify-content-md-end">
            <% if @recipe[:tags].present? %>
              <% @recipe[:tags].each do |tag| %>
                <span class="badge bg-success col-2"><%= tag %></span>
              <% end %>
            <% end %>
          </div>
          <div class="row p-2">
            <h4><%= markdown(@recipe[:description]) %></h4>
          </div>
          <div class="row p-2">
            <% if @recipe[:chef].present? %>
              <h5>Chef <b><%= @recipe[:chef] %></b></h5>
            <% end %>
          </div>
        </div>
      </div>
      <div class="row p-5">
        <%= link_to 'Back', root_path, class: 'btn btn-outline-primary col-2' %>
      </div>
    </div>   
</div>